config/routes.rb
Rails.application.routes.draw do
  
  post 'books/index' => 'books#create'
  get 'books/index' => 'books#index', as: 'index_book'
  
  get 'books/:id' => 'books#show',as:'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  
  root to: 'homes#top'

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to book_path(@book.id)
  end
  def index
    @books = Book.all  
    @book = Book.new  
  end
  
  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)  
  end
  
  def destroy
    book = Book.find(params[:id])  
    book.destroy 
    redirect_to index_book_path(book.id)  
  end
  
   private
  def book_params
    params.require(:book).permit(:title, :body)
  end
 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>


<%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Update Book' %>
  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to "Back", index_book_path(@book.id) %>
  
  
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

 <p>Title</p>
  <p>Body</p>
<% @books.each do |book| %>

 
  <h4></h4>
  <span>
    <%= link_to book.title, book_path(book.id) %>
  </span>
  <span>
    <%= link_to book.body, book_path(book.id) %>
  </span>
  <%= link_to "Show", book_path(book.id) %>
  <%= link_to "Edit", edit_book_path(book.id) %>
  <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
  
<% end %>
<h1>New book</h1>
  <%= form_with model: @book, url: '/books/index', method: :post do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h2>Title:</h2>
<p><%= @book.title %></p>

<h2>Body</h2>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", index_book_path(@book.id) %>

app/views/homes/top.html.erb
  <h1>ようこそ Bookers へ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><a href="books/index">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>